{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.disko = {
    lib,
    config,
    ...
  }: {
    # 1. Disk Topology Configuration
    imports = [inputs.disko.nixosModules.disko];
    disko.devices = {
      disk = {
        main = {
          type = "disk";
          device = config.disks.system;
          content = {
            type = "gpt";
            partitions = {
              ESP = {
                priority = 1;
                name = "ESP";
                size = "512M";
                type = "EF00";
                content = {
                  type = "filesystem";
                  format = "vfat";
                  mountpoint = "/boot";
                  mountOptions = ["defaults" "umask=0077"];
                };
              };
              root = {
                size = "100%";
                content = {
                  type = "btrfs";
                  extraArgs = ["-f"];
                  subvolumes = {
                    "@root" = {
                      mountpoint = "/";
                      mountOptions = ["compress=zstd" "noatime"];
                    };
                    "@root-blank" = {};
                    "@persist" = {
                      mountpoint = "/persist";
                      mountOptions = ["compress=zstd" "noatime"];
                    };
                    "@nix" = {
                      mountpoint = "/nix";
                      mountOptions = ["compress=zstd" "noatime"];
                    };
                  };
                };
              };
            };
          };
        };
      };
    };

    # 2. Rollback Logic tied cleanly to this layout
    boot.initrd = {
      supportedFilesystems = ["btrfs"];
      postDeviceCommands = lib.mkAfter ''
        mkdir /btrfs_tmp
        # Using the exact partlabel generated by Disko's naming convention
        mount /dev/disk/by-partlabel/disk-main-root /btrfs_tmp

        if [ -e /btrfs_tmp/@root ]; then
            mkdir -p /btrfs_tmp/old_roots
            timestamp=$(date +%Y-%m-%d_%H:%M:%S)
            mv /btrfs_tmp/@root "/btrfs_tmp/old_roots/$timestamp"
        fi

        # Re-create pristine root from our empty baseline subvolume
        btrfs subvolume snapshot /btrfs_tmp/@root-blank /btrfs_tmp/@root
        umount /btrfs_tmp
      '';
    };
  };
}
